import Head from "next/head";
import { getCsrfToken, getSession, useSession } from "next-auth/react";

export default function Home() {
  async function clickHandler() {
    const session = await getSession();
    console.log(session);
  }

  async function csrfToken() {
    const csrfToken = await getCsrfToken();
    console.log(csrfToken);
    /* ... */
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hello
        <button onClick={clickHandler}>getSession</button>
        <button onClick={csrfToken}>csrf Token</button>
      </main>
    </>
  );
}
